title: "Raul Castellanos"
author: "Raul Castellanos"
description: "University of Chicago"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout 

show_social: true 
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "https://drive.google.com/file/d/1OBcHuwU1RrUJ-noM1Ir7VjzhyE-h6owl/view?usp=drive_link", title: "CV"}
  - {title: "CV", url: "https://drive.google.com/file/d/1OBcHuwU1RrUJ-noM1Ir7VjzhyE-h6owl/view?usp=drive_link"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:raulcastellanos@uchicago.edu"}
  - {title: Github, icon: github, url: "https://github.com/rulocastellanos"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/rulocastellanos"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
